// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package buffer

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

// CreateIdeaCreateIdea includes the requested fields of the GraphQL type Idea.
// The GraphQL type's documentation follows.
//
// Ideas are the main entity in the create space
type CreateIdeaCreateIdea struct {
	Typename string `json:"__typename"`
	// Unique identifier for the idea
	Id string `json:"id"`
}

// GetTypename returns CreateIdeaCreateIdea.Typename, and is useful for accessing the field via an interface.
func (v *CreateIdeaCreateIdea) GetTypename() string { return v.Typename }

// GetId returns CreateIdeaCreateIdea.Id, and is useful for accessing the field via an interface.
func (v *CreateIdeaCreateIdea) GetId() string { return v.Id }

// CreateIdeaCreateIdeaCreateIdeaPayload includes the requested fields of the GraphQL interface CreateIdeaPayload.
//
// CreateIdeaCreateIdeaCreateIdeaPayload is implemented by the following types:
// CreateIdeaCreateIdea
// CreateIdeaCreateIdeaIdeaResponse
// CreateIdeaCreateIdeaInvalidInputError
// CreateIdeaCreateIdeaLimitReachedError
// CreateIdeaCreateIdeaUnauthorizedError
// CreateIdeaCreateIdeaUnexpectedError
// The GraphQL type's documentation follows.
//
// createIdea response (including errors)
type CreateIdeaCreateIdeaCreateIdeaPayload interface {
	implementsGraphQLInterfaceCreateIdeaCreateIdeaCreateIdeaPayload()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *CreateIdeaCreateIdea) implementsGraphQLInterfaceCreateIdeaCreateIdeaCreateIdeaPayload() {}
func (v *CreateIdeaCreateIdeaIdeaResponse) implementsGraphQLInterfaceCreateIdeaCreateIdeaCreateIdeaPayload() {
}
func (v *CreateIdeaCreateIdeaInvalidInputError) implementsGraphQLInterfaceCreateIdeaCreateIdeaCreateIdeaPayload() {
}
func (v *CreateIdeaCreateIdeaLimitReachedError) implementsGraphQLInterfaceCreateIdeaCreateIdeaCreateIdeaPayload() {
}
func (v *CreateIdeaCreateIdeaUnauthorizedError) implementsGraphQLInterfaceCreateIdeaCreateIdeaCreateIdeaPayload() {
}
func (v *CreateIdeaCreateIdeaUnexpectedError) implementsGraphQLInterfaceCreateIdeaCreateIdeaCreateIdeaPayload() {
}

func __unmarshalCreateIdeaCreateIdeaCreateIdeaPayload(b []byte, v *CreateIdeaCreateIdeaCreateIdeaPayload) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Idea":
		*v = new(CreateIdeaCreateIdea)
		return json.Unmarshal(b, *v)
	case "IdeaResponse":
		*v = new(CreateIdeaCreateIdeaIdeaResponse)
		return json.Unmarshal(b, *v)
	case "InvalidInputError":
		*v = new(CreateIdeaCreateIdeaInvalidInputError)
		return json.Unmarshal(b, *v)
	case "LimitReachedError":
		*v = new(CreateIdeaCreateIdeaLimitReachedError)
		return json.Unmarshal(b, *v)
	case "UnauthorizedError":
		*v = new(CreateIdeaCreateIdeaUnauthorizedError)
		return json.Unmarshal(b, *v)
	case "UnexpectedError":
		*v = new(CreateIdeaCreateIdeaUnexpectedError)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing CreateIdeaPayload.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for CreateIdeaCreateIdeaCreateIdeaPayload: "%v"`, tn.TypeName)
	}
}

func __marshalCreateIdeaCreateIdeaCreateIdeaPayload(v *CreateIdeaCreateIdeaCreateIdeaPayload) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *CreateIdeaCreateIdea:
		typename = "Idea"

		result := struct {
			TypeName string `json:"__typename"`
			*CreateIdeaCreateIdea
		}{typename, v}
		return json.Marshal(result)
	case *CreateIdeaCreateIdeaIdeaResponse:
		typename = "IdeaResponse"

		result := struct {
			TypeName string `json:"__typename"`
			*CreateIdeaCreateIdeaIdeaResponse
		}{typename, v}
		return json.Marshal(result)
	case *CreateIdeaCreateIdeaInvalidInputError:
		typename = "InvalidInputError"

		result := struct {
			TypeName string `json:"__typename"`
			*CreateIdeaCreateIdeaInvalidInputError
		}{typename, v}
		return json.Marshal(result)
	case *CreateIdeaCreateIdeaLimitReachedError:
		typename = "LimitReachedError"

		result := struct {
			TypeName string `json:"__typename"`
			*CreateIdeaCreateIdeaLimitReachedError
		}{typename, v}
		return json.Marshal(result)
	case *CreateIdeaCreateIdeaUnauthorizedError:
		typename = "UnauthorizedError"

		result := struct {
			TypeName string `json:"__typename"`
			*CreateIdeaCreateIdeaUnauthorizedError
		}{typename, v}
		return json.Marshal(result)
	case *CreateIdeaCreateIdeaUnexpectedError:
		typename = "UnexpectedError"

		result := struct {
			TypeName string `json:"__typename"`
			*CreateIdeaCreateIdeaUnexpectedError
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for CreateIdeaCreateIdeaCreateIdeaPayload: "%T"`, v)
	}
}

// CreateIdeaCreateIdeaIdeaResponse includes the requested fields of the GraphQL type IdeaResponse.
// The GraphQL type's documentation follows.
//
// createIdea response type
type CreateIdeaCreateIdeaIdeaResponse struct {
	Typename string `json:"__typename"`
	// The affected idea
	Idea CreateIdeaCreateIdeaIdeaResponseIdea `json:"idea"`
}

// GetTypename returns CreateIdeaCreateIdeaIdeaResponse.Typename, and is useful for accessing the field via an interface.
func (v *CreateIdeaCreateIdeaIdeaResponse) GetTypename() string { return v.Typename }

// GetIdea returns CreateIdeaCreateIdeaIdeaResponse.Idea, and is useful for accessing the field via an interface.
func (v *CreateIdeaCreateIdeaIdeaResponse) GetIdea() CreateIdeaCreateIdeaIdeaResponseIdea {
	return v.Idea
}

// CreateIdeaCreateIdeaIdeaResponseIdea includes the requested fields of the GraphQL type Idea.
// The GraphQL type's documentation follows.
//
// Ideas are the main entity in the create space
type CreateIdeaCreateIdeaIdeaResponseIdea struct {
	// Unique identifier for the idea
	Id string `json:"id"`
}

// GetId returns CreateIdeaCreateIdeaIdeaResponseIdea.Id, and is useful for accessing the field via an interface.
func (v *CreateIdeaCreateIdeaIdeaResponseIdea) GetId() string { return v.Id }

// CreateIdeaCreateIdeaInvalidInputError includes the requested fields of the GraphQL type InvalidInputError.
// The GraphQL type's documentation follows.
//
// Error returned when the input is invalid
type CreateIdeaCreateIdeaInvalidInputError struct {
	Typename string `json:"__typename"`
	// Error message
	Message string `json:"message"`
}

// GetTypename returns CreateIdeaCreateIdeaInvalidInputError.Typename, and is useful for accessing the field via an interface.
func (v *CreateIdeaCreateIdeaInvalidInputError) GetTypename() string { return v.Typename }

// GetMessage returns CreateIdeaCreateIdeaInvalidInputError.Message, and is useful for accessing the field via an interface.
func (v *CreateIdeaCreateIdeaInvalidInputError) GetMessage() string { return v.Message }

// CreateIdeaCreateIdeaLimitReachedError includes the requested fields of the GraphQL type LimitReachedError.
// The GraphQL type's documentation follows.
//
// Error returned when the limit is reached
type CreateIdeaCreateIdeaLimitReachedError struct {
	Typename string `json:"__typename"`
	// Error message
	Message string `json:"message"`
}

// GetTypename returns CreateIdeaCreateIdeaLimitReachedError.Typename, and is useful for accessing the field via an interface.
func (v *CreateIdeaCreateIdeaLimitReachedError) GetTypename() string { return v.Typename }

// GetMessage returns CreateIdeaCreateIdeaLimitReachedError.Message, and is useful for accessing the field via an interface.
func (v *CreateIdeaCreateIdeaLimitReachedError) GetMessage() string { return v.Message }

// CreateIdeaCreateIdeaUnauthorizedError includes the requested fields of the GraphQL type UnauthorizedError.
// The GraphQL type's documentation follows.
//
// Error returned when the user is not authorized to perform the action
type CreateIdeaCreateIdeaUnauthorizedError struct {
	Typename string `json:"__typename"`
	// Error message
	Message string `json:"message"`
}

// GetTypename returns CreateIdeaCreateIdeaUnauthorizedError.Typename, and is useful for accessing the field via an interface.
func (v *CreateIdeaCreateIdeaUnauthorizedError) GetTypename() string { return v.Typename }

// GetMessage returns CreateIdeaCreateIdeaUnauthorizedError.Message, and is useful for accessing the field via an interface.
func (v *CreateIdeaCreateIdeaUnauthorizedError) GetMessage() string { return v.Message }

// CreateIdeaCreateIdeaUnexpectedError includes the requested fields of the GraphQL type UnexpectedError.
// The GraphQL type's documentation follows.
//
// Error returned when unexpected error occurs
type CreateIdeaCreateIdeaUnexpectedError struct {
	Typename string `json:"__typename"`
	// Error message
	Message string `json:"message"`
}

// GetTypename returns CreateIdeaCreateIdeaUnexpectedError.Typename, and is useful for accessing the field via an interface.
func (v *CreateIdeaCreateIdeaUnexpectedError) GetTypename() string { return v.Typename }

// GetMessage returns CreateIdeaCreateIdeaUnexpectedError.Message, and is useful for accessing the field via an interface.
func (v *CreateIdeaCreateIdeaUnexpectedError) GetMessage() string { return v.Message }

// CreateIdeaResponse is returned by CreateIdea on success.
type CreateIdeaResponse struct {
	// Create a new idea with the given content and metadata
	CreateIdea CreateIdeaCreateIdeaCreateIdeaPayload `json:"-"`
}

// GetCreateIdea returns CreateIdeaResponse.CreateIdea, and is useful for accessing the field via an interface.
func (v *CreateIdeaResponse) GetCreateIdea() CreateIdeaCreateIdeaCreateIdeaPayload {
	return v.CreateIdea
}

func (v *CreateIdeaResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*CreateIdeaResponse
		CreateIdea json.RawMessage `json:"createIdea"`
		graphql.NoUnmarshalJSON
	}
	firstPass.CreateIdeaResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.CreateIdea
		src := firstPass.CreateIdea
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalCreateIdeaCreateIdeaCreateIdeaPayload(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal CreateIdeaResponse.CreateIdea: %w", err)
			}
		}
	}
	return nil
}

type __premarshalCreateIdeaResponse struct {
	CreateIdea json.RawMessage `json:"createIdea"`
}

func (v *CreateIdeaResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *CreateIdeaResponse) __premarshalJSON() (*__premarshalCreateIdeaResponse, error) {
	var retval __premarshalCreateIdeaResponse

	{

		dst := &retval.CreateIdea
		src := v.CreateIdea
		var err error
		*dst, err = __marshalCreateIdeaCreateIdeaCreateIdeaPayload(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal CreateIdeaResponse.CreateIdea: %w", err)
		}
	}
	return &retval, nil
}

// GetChannelsChannelsChannel includes the requested fields of the GraphQL type Channel.
// The GraphQL type's documentation follows.
//
// Channel entity
type GetChannelsChannelsChannel struct {
	// The ID of the channel
	// Source: mapper from channel collection - channel._id
	// Defined in: both proposals
	Id string `json:"id"`
	// The name of the channel - the handle name, username, etc.
	// Source: mapper from channel collection - channel.name
	// Defined in: both proposals
	Name string `json:"name"`
	// Represents the social network
	// Source: mapper from channel collection - channel.serviceType
	// Defined in: both proposals
	Service Service `json:"service"`
}

// GetId returns GetChannelsChannelsChannel.Id, and is useful for accessing the field via an interface.
func (v *GetChannelsChannelsChannel) GetId() string { return v.Id }

// GetName returns GetChannelsChannelsChannel.Name, and is useful for accessing the field via an interface.
func (v *GetChannelsChannelsChannel) GetName() string { return v.Name }

// GetService returns GetChannelsChannelsChannel.Service, and is useful for accessing the field via an interface.
func (v *GetChannelsChannelsChannel) GetService() Service { return v.Service }

// GetChannelsResponse is returned by GetChannels on success.
type GetChannelsResponse struct {
	// Fetch all channels for the organization taking into account the current's user permissions
	Channels []GetChannelsChannelsChannel `json:"channels"`
}

// GetChannels returns GetChannelsResponse.Channels, and is useful for accessing the field via an interface.
func (v *GetChannelsResponse) GetChannels() []GetChannelsChannelsChannel { return v.Channels }

// The list of services that can be authorized.
type Service string

const (
	ServiceInstagram      Service = "instagram"
	ServiceFacebook       Service = "facebook"
	ServiceTwitter        Service = "twitter"
	ServiceLinkedin       Service = "linkedin"
	ServicePinterest      Service = "pinterest"
	ServiceTiktok         Service = "tiktok"
	ServiceGooglebusiness Service = "googlebusiness"
	ServiceStartpage      Service = "startPage"
	ServiceMastodon       Service = "mastodon"
	ServiceYoutube        Service = "youtube"
	ServiceThreads        Service = "threads"
	ServiceBluesky        Service = "bluesky"
)

var AllService = []Service{
	ServiceInstagram,
	ServiceFacebook,
	ServiceTwitter,
	ServiceLinkedin,
	ServicePinterest,
	ServiceTiktok,
	ServiceGooglebusiness,
	ServiceStartpage,
	ServiceMastodon,
	ServiceYoutube,
	ServiceThreads,
	ServiceBluesky,
}

// __CreateIdeaInput is used internally by genqlient
type __CreateIdeaInput struct {
	OrganizationId string `json:"organizationId"`
	Title          string `json:"title"`
	Text           string `json:"text"`
}

// GetOrganizationId returns __CreateIdeaInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__CreateIdeaInput) GetOrganizationId() string { return v.OrganizationId }

// GetTitle returns __CreateIdeaInput.Title, and is useful for accessing the field via an interface.
func (v *__CreateIdeaInput) GetTitle() string { return v.Title }

// GetText returns __CreateIdeaInput.Text, and is useful for accessing the field via an interface.
func (v *__CreateIdeaInput) GetText() string { return v.Text }

// __GetChannelsInput is used internally by genqlient
type __GetChannelsInput struct {
	OrganizationId string `json:"organizationId"`
}

// GetOrganizationId returns __GetChannelsInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__GetChannelsInput) GetOrganizationId() string { return v.OrganizationId }

// The mutation executed by CreateIdea.
const CreateIdea_Operation = `
mutation CreateIdea ($organizationId: ID!, $title: String!, $text: String!) {
	createIdea(input: {organizationId:$organizationId,content:{title:$title,text:$text}}) {
		__typename
		... on Idea {
			id
		}
		... on IdeaResponse {
			idea {
				id
			}
		}
		... on InvalidInputError {
			message
		}
		... on UnauthorizedError {
			message
		}
		... on UnexpectedError {
			message
		}
		... on LimitReachedError {
			message
		}
	}
}
`

func CreateIdea(
	ctx_ context.Context,
	client_ graphql.Client,
	organizationId string,
	title string,
	text string,
) (data_ *CreateIdeaResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateIdea",
		Query:  CreateIdea_Operation,
		Variables: &__CreateIdeaInput{
			OrganizationId: organizationId,
			Title:          title,
			Text:           text,
		},
	}

	data_ = &CreateIdeaResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetChannels.
const GetChannels_Operation = `
query GetChannels ($organizationId: OrganizationId!) {
	channels(input: {organizationId:$organizationId}) {
		id
		name
		service
	}
}
`

func GetChannels(
	ctx_ context.Context,
	client_ graphql.Client,
	organizationId string,
) (data_ *GetChannelsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetChannels",
		Query:  GetChannels_Operation,
		Variables: &__GetChannelsInput{
			OrganizationId: organizationId,
		},
	}

	data_ = &GetChannelsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
